name: sellcar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  collection: 1.17.0
  dropdown_button2: 2.0.0
  expandable: 5.0.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_google_places: 
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
  flutter_plugin_android_lifecycle: 2.0.9
  flutter_staggered_grid_view: 0.6.2
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  google_maps: 6.2.0
  google_maps_flutter: 2.1.8
  google_maps_flutter_platform_interface: 2.2.1
  google_maps_flutter_web: 0.4.0+1
  intl: 0.17.0
  json_path: 0.4.1
  package_info_plus: 3.1.0
  package_info_plus_platform_interface: 2.0.1
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: 6.0.4
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  smooth_page_indicator: 1.0.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  material_design_icons_flutter: 6.0.7096


  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/