// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEhPvz2h13ucTJX9WAHEAb-NzNThvY-U8',
    appId: '1:826461921789:web:ec22a7dd82d2b54b66f994',
    messagingSenderId: '826461921789',
    projectId: 'flutterproject-6bd0c',
    authDomain: 'flutterproject-6bd0c.firebaseapp.com',
    databaseURL: 'https://flutterproject-6bd0c-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-6bd0c.appspot.com',
    measurementId: 'G-NPHG2KW1X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmfDQeMka8UVGRTWZ2OnCwzWw7fe9zuos',
    appId: '1:826461921789:android:796dcfff8e1ad7ba66f994',
    messagingSenderId: '826461921789',
    projectId: 'flutterproject-6bd0c',
    databaseURL: 'https://flutterproject-6bd0c-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-6bd0c.appspot.com',
  );
}
